version: "3.5"
services:

  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "yUZpX336h6fPGL48"
      ACCEPT_EULA: "Y"
